name: Automation regression tests

on:
  workflow_dispatch

jobs:
  regression-tests:
    runs-on: windows-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v3
        with:
          ref: 'main'
      
      - name: Run Cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome

      - name: "Upload Cypress videos"
        if: '!cancelled()'
        uses: actions/upload-artifact@v3
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore

      - name: "Upload Cypress screenshots"
        if: '!cancelled()'
        uses: actions/upload-artifact@v3
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore