name: Cypress tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm ci

    - name: Save video after each test
      run: |
        CYPRESS_RECORD_KEY=${{ env.CYPRESS_RECORD_KEY }} npx cypress run

    - name: Upload videos
      uses: actions/upload-artifact@v2
      with:
        name: cypress-videos
        path: cypress/videos
