name: Cypress tests

on: [push]

jobs:
  cypress-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm ci

    - name: Run Cypress tests
      run: |
        npx cypress run

    - name: Copy .mp4 files
      run: |
        xcopy /e /i cypress\videos\ mp4_videos
