name: Cypress tests

on: [push]

env:
  CI: true

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm ci

    - name: Run cypress tests
      run: |
        npx cypress run --record --key <your_cypress_record_key>

    - name: Upload video after each test
      run: |
        mv cypress/videos/*.mp4 cypress/mp4-videos/${{ env.GITHUB_RUN_ID }}/
      env:
        GITHUB_RUN_ID: ${{ env.GITHUB_RUN_ID }}

    - name: Upload video artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mp4-videos-${{ env.GITHUB_RUN_ID }}
        path: cypress/mp4-videos/${{ env.GITHUB_RUN_ID }}
        target_path: mp4-videos/${{ env.GITHUB_RUN_ID }}
