name: UP Automation regression

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-automation-regression-tests-instance-1:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          record: true
          parallel: true
          group: 'Instance 1'
          spec: UP-3565.spec.ts, UP-4097.spec.ts, UP-4130.spec.ts, UP-4131.spec.ts, UP-4132.spec.ts, UP-4133.spec.ts, UP-4135.spec.ts, UP-4138.spec.ts, UP-801.spec.ts, UP-802.spec.ts, UP-803.spec.ts, UP-810.spec.ts, UP-814.spec.ts, UP-815.spec.ts, UP-816.spec.ts
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-automation-regression-tests-instance-2:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          record: true
          parallel: true
          group: 'Instance 2'
          spec: cypress/e2e/Tests/UP-802.spec.ts,cypress/e2e/Tests/UP-803.spec.ts
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-automation-regression-tests-instance-3:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          record: true
          parallel: true
          group: 'Instance 3'
          spec: cypress/e2e/Tests/UP-817.spec.ts,cypress/e2e/Tests/UP-818.spec.ts
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
