name: UP Automation regression

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-automation-regression-tests:
    runs-on: windows-latest
    strategy:
      matrix:
        instance: [1, 2, 3, 4]  # Definim 4 instanțe pentru a rula în paralel
    steps:
      - run: git config --global url."https://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@github.com/".insteadOf https://github.com/
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          record: true
          parallel: true
          group: ${{ matrix.instance }}  # Grupăm testele în funcție de instanța de rulare
        env:
          # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
          # in GitHub repo → Settings → Secrets → Actions
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
