name: UP Automation regression

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-automation-regression-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cypress configuration
        run: |
          # Download your Cypress configuration file from repository secrets
          curl -o cypress.config.js https://raw.githubusercontent.com/<user>/<repo>/master/cypress.config.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Cypress run (parallelized)
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          record: true
          parallel: true
          parallel-group-size: 30  # Divide tests into groups of 30 each
          parallel-mode: "instance"  # Specify "instance" for Cypress Cloud execution
          record-key: ${{ secrets.CYPRESS_RECORD_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload test results (optional)
        # Leave this step empty if you don't have specific actions to perform for uploading test results
