name: UP Automation regression

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  
  run-automation-regression-tests:
    runs-on: windows-latest
    strategy:
      matrix:
        instance: [1, 2, 3] # Define a matrix of 3 instances
    steps:
      - run: git config --global url."https://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@github.com/".insteadOf https://github.com/
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          record: true
          parallel: true
          parallel-group-size: 30  # Specify the number of tests to run per group
          parallel-mode: "instance"  # Specify "instance" for Cypress Cloud execution
          record-key: ${{ secrets.CYPRESS_RECORD_KEY }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
