name: UP Automation regression

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-automation-regression-tests:
    runs-on: windows-latest
    strategy:
      matrix:
        instances: [1, 2, 3, 4, 5] # Specificăm 5 instanțe paralele
        chunk: ${{ ceil(90 / 5) }} # Calculăm numărul de teste per instanță (90 teste împărțite în 5 instanțe)
    steps:
      - run: git config --global url."https://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@github.com/".insteadOf https://github.com/
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          record: true
          parallel: true # Activăm paralelizarea
          group: 'Instance ${{ matrix.instances }}' # Grupăm instanțele paralele
          spec: test${{ matrix.instances }}.js # Specificăm fișierele de test pentru fiecare instanță
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
