name: UP Automation regression

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-automation-regression-tests:
    runs-on: windows-latest
    strategy:
      matrix:
        instances: [1, 2, 3] # Definim 3 instanțe paralele
    steps:
      - run: git config --global url."https://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@github.com/".insteadOf https://github.com/

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Calculate test range
        id: calculate_range
        run: |
          $start_test = ($env:INSTANCE - 1) * 30 + 1
          $end_test = $start_test + 29
          echo "::set-output name=start_test::$start_test"
          echo "::set-output name=end_test::$end_test"

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          record: true
          parallel: true
          group: 'Instance ${{ matrix.instances }}'
          spec: cypress/e2e/Tests/UP-*.spec.ts
        env:
          INSTANCE: ${{ matrix.instances }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
