name: UP Automation regression

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-automation-regression-tests-instance-1:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Calculate test range for Instance 1
        id: calc_range_1
        run: |
          total_tests=90
          tests_per_instance=18
          start_test=$((1 + (tests_per_instance * (1 - 1))))
          end_test=$(($start_test + tests_per_instance - 1))
          echo "::set-output name=start_test::$start_test"
          echo "::set-output name=end_test::$end_test"
      - name: Cypress run Instance 1
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          record: true
          parallel: true
          group: 'Instance 1'
          spec: cypress/e2e/Tests/UP-${{ steps.calc_range_1.outputs.start_test }}.spec.ts-cypress/e2e/Tests/UP-${{ steps.calc_range_1.outputs.end_test }}.spec.ts
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-automation-regression-tests-instance-2:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Calculate test range for Instance 2
        id: calc_range_2
        run: |
          total_tests=90
          tests_per_instance=18
          start_test=$((1 + (tests_per_instance * (2 - 1))))
          end_test=$(($start_test + tests_per_instance - 1))
          echo "::set-output name=start_test::$start_test"
          echo "::set-output name=end_test::$end_test"
      - name: Cypress run Instance 2
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          record: true
          parallel: true
          group: 'Instance 2'
          spec: cypress/e2e/Tests/UP-${{ steps.calc_range_2.outputs.start_test }}.spec.ts-cypress/e2e/Tests/UP-${{ steps.calc_range_2.outputs.end_test }}.spec.ts
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-automation-regression-tests-instance-3:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Calculate test range for Instance 3
        id: calc_range_3
        run: |
          total_tests=90
          tests_per_instance=18
          start_test=$((1 + (tests_per_instance * (3 - 1))))
          end_test=$(($start_test + tests_per_instance - 1))
          echo "::set-output name=start_test::$start_test"
          echo "::set-output name=end_test::$end_test"
      - name: Cypress run Instance 3
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          record: true
          parallel: true
          group: 'Instance 3'
          spec: cypress/e2e/Tests/UP-${{ steps.calc_range_3.outputs.start_test }}.spec.ts-cypress/e2e/Tests/UP-${{ steps.calc_range_3.outputs.end_test }}.spec.ts
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-automation-regression-tests-instance-4:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Calculate test range for Instance 4
        id: calc_range_4
        run: |
          total_tests=90
          tests_per_instance=18
          start_test=$((1 + (tests_per_instance * (4 - 1))))
          end_test=$(($start_test + tests_per_instance - 1))
          echo "::set-output name=start_test::$start_test"
          echo "::set-output name=end_test::$end_test"
      - name: Cypress run Instance 4
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          record: true
          parallel: true
          group: 'Instance 4'
          spec: cypress/e2e/Tests/UP-${{ steps.calc_range_4.outputs.start_test }}.spec.ts-cypress/e2e/Tests/UP-${{ steps.calc_range_4.outputs.end_test }}.spec.ts
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  run-automation-regression-tests-instance-5:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Calculate test range for Instance 5
        id: calc_range_5
        run: |
          total_tests=90
          tests_per_instance=18
          start_test=$((1 + (tests_per_instance * (5 - 1))))
          end_test=$(($start_test + tests_per_instance - 1))
          echo "::set-output name=start_test::$start_test"
          echo "::set-output name=end_test::$end_test"
      - name: Cypress run Instance 5
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          record: true
          parallel: true
          group: 'Instance 5'
          spec: cypress/e2e/Tests/UP-${{ steps.calc_range_5.outputs.start_test }}.spec.ts-cypress/e2e/Tests/UP-${{ steps.calc_range_5.outputs.end_test }}.spec.ts
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
