name: UP Automation regression

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-automation-regression-tests:
    runs-on: windows-latest
    strategy:
      matrix:
        container: [1, 2, 3] # Define 3 parallel instances
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Cypress
        uses: cypress-io/github-action@v6
        with:
          install: true
          # Install additional Cypress dependencies if needed
          # For example: cypress-image-snapshot, cypress-cucumber
          # install-other-dependencies: true
          # other-dependencies: ["cypress-image-snapshot", "cypress-cucumber"]

      - name: Run Cypress tests (Parallel)
        uses: cypress-io/github-action@v6
        with:
          browser: electron
          record: true # Optional, adjust based on your needs
          parallel: true
          env:
            # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
            # in GitHub repo → Settings → Secrets → Actions
            CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
            # Creating a token https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload test results (Optional)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Cypress Test Results
          path: cypress/results

